algoritmo "Enquanto n"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

n:inteiro

inicio

escreva("Digite um número inteiro qualquer: ")
leia(n)
enquanto (N>0) faca
    escreval (n)
    n:=n - 1
fimenquanto

fimalgoritmo