algoritmo "de 1 a 100"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

n, i:inteiro

inicio
escreva("Segue abaixo todas as somas de 1 a 100: ")
n:=0
i:=1
enquanto (n<=100) faca
    escreval (n)
n:=n+i
fimenquanto

fimalgoritmo