algoritmo "ParouImpar:)"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

N:inteiro

inicio

escreval ("Digite seu número: ")
leia(N)
se (N % 2=0) entao
    escreval ("Seu número é par")
senao
    escreval ("Seu número é ímpar")
fimse

fimalgoritmo